# Build and test the mod
name: Build and test

on:
  workflow_dispatch:
    inputs:
      timeout:
        description: 'Timeout for runServer (seconds)'
        required: false
        default: 90
        type: number
      client-only:
        description: 'Do not execute runServer'
        required: false
        default: false
        type: boolean

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Build
        uses: ./.github/actions/build_setup
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Compile the mod
        run: ./gradlew --scan --build-cache --info --stacktrace assemble

      - name: Upload Jars
        uses: actions/upload-artifact@v4
        with:
          name: GTExpert-Core
          path: build/libs/*.jar
          retention-days: 31

      - name: Run post-build checks
        id: build_mod
        run: ./gradlew --build-cache --info --stacktrace build

      - name: Run server for ${{ inputs.timeout }} seconds
        if: ${{ !inputs.client-only }}
        run: |
          mkdir -p run
          echo "eula=true" > run/eula.txt
          # Set a constant seed with a village at spawn
          echo "stop" > run/stop.txt
          timeout ${{ inputs.timeout }} ./gradlew --build-cache --info --stacktrace runServer 2>&1 < run/stop.txt | tee -a server.log || true

      - name: Test no errors reported during server run
        if: ${{ !inputs.client-only }}
        run: |
          chmod +x ./scripts/test_no_error_reports
          ./scripts/test_no_error_reports
